#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Power_project

COMPONENT_ADD_INCLUDEDIRS := components/include

COMPONENT_ADD_INCLUDEDIRS := components/src

COMPONENT_ADD_LDFLAGS += -u custom_app_desc

include $(IDF_PATH)/make/project.mk
